---
# •••••••••• Stats Bar •••••••••••••
# If you want you can add Stuff like Money, Rank
# Make sure to add the plugins for the api to work
# Plugins Needed: EcomonyAPI, PurePerms, KDR
# ••••••••••••••••••••••••••••
# Avaiable KeyWords:
# {display_name} , {name}
# {x} , {y} , {z}
# {world} , {world_players}
# {players} , {max_online}
# {hour} , {minute} , {second}
# {ping} , {ip}
#
# EconomyAPI
# {money}
#
# PurePerms
# {rank} , {prefix} , {suffix}
#
# KDR
# {kdr} , {kills} , {deaths}
#
# ••••••••••••••••••••••••••••
# To go to the next line use \n or {EOL}
# For Color Codes use & or §
# Example:
# - "{25%} &aMoney: &b{money}"
# ••••••••••••••••••••••••••••
head-message: "main text"
changing-messages:
 - "{0%} YOUR TEXT"
 - "{20%} YOUR TEXT"
 - "{40%} YOUR TEXT"
 - "{60%} YOUR TEXT"
 - "{80%} YOUR TEXT"
 - "{100%} YOUR TEXT"
change-speed: 8
worlds: []
...
